import {
  CATEGORY_NAME_EXISTS_INJECTION_TOKEN,
  MAX_LENGTH_RENDERER_INJECTION_TOKEN,
  MIN_LENGTH_RENDERER_INJECTION_TOKEN,
  REQUIRED_RENDERER_INJECTION_TOKEN,
} from './tokens/injection-tokens';

export const ErrorStrategiesMap = new Map([
  ['required', REQUIRED_RENDERER_INJECTION_TOKEN],
  ['maxlength', MAX_LENGTH_RENDERER_INJECTION_TOKEN],
  ['minlength', MIN_LENGTH_RENDERER_INJECTION_TOKEN],
  ['categoryExists', CATEGORY_NAME_EXISTS_INJECTION_TOKEN],
]);
